### ISSUE TITLE
turret arc could be simplified to one value instead of two as a min and max arc

### ISSUE THREAD

**Issue by ty1221pro** [endless-sky/endless-sky#10108]
### Problem Description

I just tried the turret arcs and was frusterated with it having a min and max value it would pobably just be simpler having it just one value that works with the facing angle of the turret..

### Related Issue Links

there is really no links

### Desired Solution

the desired solution is to make creating turret arcs simpler by making the two values just be on generalized value for the angle that will always work as the min and max arc that only depends on the turrets facing angle.

### Alternative Approaches

I really cant think of a better alternive as the min and max arc would just be on angle value that relies on turret facing angle.

### Additional Context

the context is that if you have a turret with a facing angle of 90 degrees then have a single generalized arc value that works as the min and max angle arc relative to the facing arc of the turret. so the turret is "angle" 90. then the arc should just be "arc" 180 as one value for the min and max meaning it will turn 180 degrees both ways from its facing angle.

**Comment by ty1221pro** [comment]
I just found the perfect image
![download](https://github.com/endless-sky/endless-sky/assets/68208406/0346930c-99f4-4ffb-aa58-0a36612caeee)

**Comment by ty1221pro** [comment]
as thats how the generalized arc should work relative to the facing angle

**Comment by ty1221pro** [comment]
meaning just one value works both ways

**Comment by Zitchas** [comment]
That is a clever idea, however as a content creator, I don't necessarily always want the facing angle to be the middle of the arc. This seems a situation where it could be better resolved by having a decent set of examples of different configurations to get people started, rather than just reducing possibilities.

**Comment by 43897689431805741092** [comment]
I assumed this was requesting it be so that, if only one value is specified, the game uses a symmetrical arc, and you still have the option of specifying two numbers for an asymmetrical one.

**Comment by Zitchas** [comment]
Hmm, the original post repeatedly talks about simplifying things down to a single value, so it appeared to be advocating for replacing the system with a single value.

That being said, at first glance, definitely agree that having the *option* to use just a single value that is automatically centered on facing would certainly be a simpler and potentially beneficial addition. I definitely wouldn't want it to *replace* having min and max value, though.

**Comment by binaryspica** [comment]
The problem on this idea is when you want the turret to be not able to rotate much for some direction, while you want to dictate the idle direction of the gun but it's not the middle ground. 

Such as the you want the turret on the front right side to be facing toward by default but the turret can only go 15º left while it can go about 105º right. On your idea it have to be facing 45º at the beginning and have to waste the time before it arranged to the front when the enemy is on their front. 

Although it's a corner case but, Even if you have a turret on the left side and have a 180º toward left(so up to direct front to rear) but you want it to be facing front or it needs the time to turn to the front.

**Comment by Zitchas** [comment]
Yes, exactly.

**Comment by ty1221pro** [comment]
> Hmm, the original post repeatedly talks about simplifying things down to a single value, so it appeared to be advocating for replacing the system with a single value.
> 
> That being said, at first glance, definitely agree that having the _option_ to use just a single value that is automatically centered on facing would certainly be a simpler and potentially beneficial addition. I definitely wouldn't want it to _replace_ having min and max value, though.

I actually did not think of having both systems in place and thats better than choosing one or the other

**Comment by ty1221pro** [comment]
So I agree with Zitchas

**Comment by TomGoodIdea** [comment]
Now that this has become mainly a feature request, I want to say that having both systems would make the behavior differ completely depending on how many values you put for the arc. I'm not sure if that would really make things simpler.
