### ISSUE TITLE
Unusual mass scanning after update 0.9.5.1

### ISSUE THREAD

**Issue by pasu11** [endless-sky/endless-sky#2029]
Is it a bug that after the new update 0.9.5.1, my ships got scanned by each ship in the sector. The message area is constantly spammed with " x ship is attempting to scan you."
This happens when I depart with a fleet.

![screenshot at 2017-01-18 13-41-57](https://cloud.githubusercontent.com/assets/25207448/22078124/009194de-dd85-11e6-98ba-8ef54b1f7dfd.png)

**Comment by KiLEdEnNis** [comment]
every ship with a scanner scans every ship it can
it should be changed so that only 1 ship of a  government scans you until you leave the system

**Comment by Phil-Morley** [comment]
it is attempting and not succeeding so tries again? Started a fresh pilot with .95 and in the mission to scan the cruiser I just get 'attempting to scan' and thats it, it doesnt actually finish the scan. I tried with other ships and I cannot complete a scan always just the 'attempting' to do it.

**Comment by KiLEdEnNis** [comment]
try using multiple scanners

**Comment by Phil-Morley** [comment]
same thing (tried with 2 then 5)

**Comment by Bladewood** [comment]
Did you try holding the scan key?

**Comment by Phil-Morley** [comment]
yes holding it down worked

**Comment by KiLEdEnNis** [comment]
didn't the scanner description or tooltip say "hold down the button to scan"?

**Comment by Amazinite** [comment]
Maybe the Navy ships aren't holding the button either. :)

**Comment by endless-sky** [comment]
I think this was fixed a while ago. Has anyone seen it in 0.9.6+?

**Comment by tehhowch** [comment]
You'll get a scan notification for every ship in your fleet that gets scanned.. That still happens. They do complete their scans. I haven't checked what happens / is displayed when having interference plating.
