### ISSUE TITLE
Game freeze on boarding hostile ships

### ISSUE THREAD

**Issue by stinkray** [endless-sky/endless-sky#2516]
Version: git master as of 2017/05/12
Environment: Fedora 25 GNOME on Wayland
 
Description: Upon boarding a disabled hostile ship, such as a surveillance drone you shot, instead of showing the boarding screen, the game screen will freeze and sounds will stall.

Steps to reproduce:
1. Compile game from git master (git clone https://github.com/endless-sky/endless-sky && cd endless-sky && scons)
2. Start game (./endless-sky)
2. Target a surveillance drone (or any other ship)
3. Fire upon ship until it is disabled
4. Press B to board while ship is still targeted

Expected Result: Boarding menu will appear, giving the option to plunder outfits such as a surveillance module

**Comment by Bladewood** [comment]
...
Okay.

Happens on Windows 10 as well.

**Comment by tehhowch** [comment]
16.04 with g++ version 5.4.0 20160609
also unable to open the BoardingPanel interface.

**Comment by afrantisak** [comment]
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

cit iterator (also sit) is nil in line 96 of BoardingPanel.cpp:

```
#0  0x00007f2a89b23a70 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00000000004413c7 in std::_Rb_tree_const_iterator<std::pair<Outfit const* const, int> >::operator++ (this=0x7ffef6bebd40) at /usr/include/c++/5/bits/stl_tree.h:284
#2  0x0000000000459455 in BoardingPanel::BoardingPanel (this=0x33afec0, player=..., victim=std::shared_ptr (count 3, weak 6) 0x7f2a4cc38630) at source/BoardingPanel.cpp:96
#3  0x000000000054b602 in MainPanel::Step (this=0x33b6110) at source/MainPanel.cpp:113
#4  0x0000000000673c97 in UI::StepAll (this=0x7ffef6bec060) at source/UI.cpp:109
#5  0x000000000067a9dc in main (argc=1, argv=0x7ffef6becbe8) at source/main.cpp:290
```

**Comment by EndrosG** [comment]
I am not sure, and I dont have the bugged code on my local desktop yet, but **please** try the following:

```
81 -		bool shipIsFirst = (cit == victim->Outfits().end() || sit->first <= cit->first);
81 +		bool shipIsFirst = (cit == victim->Cargo().Outfits().end() || sit->first <= cit->first);
```
The Cargo(). is missing in the cit == test -- compare with line 74.

**Comment by tehhowch** [comment]
That alone is not enough to fix the issue

**Comment by tehhowch** [comment]
PR incoming with the fix (the booleans wouldn't handle the case where they were also at the end)

**Comment by endless-sky** [comment]
Fixed in f0489de.

**Comment by tehhowch** [comment]
f0489de does NOT fix the issue - boarding to plunder still crashes to desktop

**Comment by tehhowch** [comment]
The problem is possibly fixable by only one check (my now-closed PR 2517 had two):
`bool cargoIsFirst = (sit == victim->Outfits().end() || cit->first <= sit->first) && cit != victim->Cargo().Outfits().end();`
Without that, boarding operations that yield plunder screens never finish loading, requiring the game to be force closed.
With that one line change, boarding operations that yield plunder screens work.
I do not have any "hostile ships with outfits in cargo" with which to test against, but with my added change, the player can properly plunder outfits from ships' hulls, and ammunition into their secondary weapon (even when player's cargo hold is full). The other check (as seen in #2517) may be needed to address the case where outfits are in the target's cargo hold as well.

Furthermore it is rather upsetting that f0489de was pushed even though testing reported in this very thread stated it was not sufficient to fix the issue - it seems that this issue's comments were entirely disregarded or ignored, and that the solution was not tested before being pushed to master.

**Comment by tehhowch** [comment]
98aa866 fixes this for me (as above, I don't have a simple way to test plunder of ships with cargo'd outfits.)
