### ISSUE TITLE
Eye is treated as a planet instead of a wormhole

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2794]
http://steamcommunity.com/app/404410/discussions/0/1458455461483175693/

Though, it's not happening on my end...
Maybe it's fine for people already past that point. @toilethinges suspects that it is related to https://github.com/endless-sky/endless-sky/commit/1a5ac0220f56ea72cc0176bf3453fba38c31d711#diff-c9a5099a3f432ad37ea993a9a623428eR773.

**Comment by Rob59er** [comment]
Note: This is a wanderer playthrough that has only been happening during the 0.9.7 release

**Comment by endless-sky** [comment]
Can you post a saved game?

**Comment by Rob59er** [comment]
[Nudnuii  Maiarone copy.txt](https://github.com/endless-sky/endless-sky/files/1166644/Nudnuii.Maiarone.copy.txt)

**Comment by endless-sky** [comment]
Should be fixed in commit 1fcfd4b.

**Comment by Rob59er** [comment]
and now I wait

**Comment by gunqqer** [comment]
if that commit was in the release on steam that was 8.1kb it didn't fix it.

**Comment by Bladewood** [comment]
It won't fix it if you're already past that event. Try reloading to a save before it (assuming one exists).

**Comment by gunqqer** [comment]
weeeeeelllll crud. Thank god we now have a log book so I can find when TF it was....

**Comment by tehhowch** [comment]
When 1fcfd4b reaches Steam, any "broken" saves should be fixed (though if the player is landed on The Eye or has accepted jobs going to The Eye, it could be rather interesting). If they are not, then 1fcfd4b did not solve the problem.

Those who do not wish to wait for the fix can change the event definition in their save file:
taken from my post to the [email forum](https://groups.google.com/forum/#!category-topic/endless-sky/54pD5G50vwg)
In the event definition that alters Sabriset, remove the line `add object "The Eye"` and replace with:
```
	object
		sprite star/g0
		distance 35.1028
		period 12.1391
	object
		sprite star/k0
		distance 77.8972
		period 12.1391
		offset 180
	object
		sprite planet/desert1
		distance 279.387
		period 47.1932
	object
		sprite planet/lava7
		distance 738.015
		period 202.613
		offset 212.423
	object
		sprite planet/desert2
		distance 1012.78
		period 325.718
	object
		sprite planet/rock5
		distance 1367.84
		period 511.237
	object "The Eye"
```
Then when your save is loaded, the `add` behavior will not be used, and the code used for first-time definitions will be used.

**Comment by gunqqer** [comment]
WHELP, I'VE GONE THROUGH ENOUGH OF THE STORY AGAIN IT'S TOO MUCH WORK TO COPY THAT IN. URGH
