### ISSUE TITLE
Ships don't explode as a result of conversation end points if they are a mission source

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4262]
**Describe the bug**
There is an inconsistency in the behavior of `launch`, `flee`, and similar conversation end points when the conversation takes place on a ship depending on if that ship was the source of a mission or if that ship was an NPC spawned by a mission; if the NPC is part of the mission, `launch` and similar will cause the NPC to explode, but if the ship is the source of the mission, these end points will not result in the explosion of the ship.

**To Reproduce**
1. Get the new pirate mutiny mission to offer upon boarding a pirate medium or heavy warship
2. Whether you launch or flee, notice how the ship does not blow up
3. Get the Tod Copper mission to offer
4. When you launch from Lord Ligonier's ship, notice how it does blow up.

**Expected behavior**
`launch`, `flee`, and similar conversation end points should behave the same when boarding a ship regardless of the circumstances of the conversation being offered from the ship. i.e. conversations triggered on offer where the ship is the source and conversations triggered on boarding a mission NPC should both cause the ship to explode if the end point causes the player to launch.

**System (please complete the following information):**
- OS: Windows 10 Home, Version 10.0.17134 Build 17134
 - Game Source: Self-compiled
 - Version: Most up to date as of this issue (cba3ae5116cac0365e4fef4bc4d807d5eca841d5)

**Additional context**
Ref: #3129, #3140, #4186

**Comment by tehhowch** [comment]
Should be an easy fix:
https://github.com/endless-sky/endless-sky/blob/cba3ae5116cac0365e4fef4bc4d807d5eca841d5/source/MainPanel.cpp#L474
`Mission::Do` takes an additional parameter (a pointer to the NPC ship) and this line doesn't have it supplied, so the default--a null pointer--is used. With no usable ship pointer, the conversation panel doesn't know anything should be scuttled.

Adding the missing `event.Target()` should be all that is needed; I'll update tomorrow.

**Comment by tehhowch** [comment]
Should be addressed by ceda5b69561bea7eb53ef1290d42c4715dcdfe7e

**Comment by Amazinite** [comment]
Can confirm.

**Comment by RPBCACUEAIIBH** [comment]
Was the fix marged to the source code? Cause I just built it from source, and it still doesn't explode...
It stops moving, with 0% Hull, and 100% shield, and if exit to the main menu it says I'm dead, but it didn't explode...

**Comment by MCOfficer** [comment]
it was, see ceda5b69561bea7eb53ef1290d42c4715dcdfe7e. @Amazinite can you repro that?

**Comment by Amazinite** [comment]
Are you referring to `die`? This issue is referring to `launch` and similar endpoints.

**Comment by RPBCACUEAIIBH** [comment]
no I'm pretty sure I put "explode" in into the code... I also used "die", but that works fine, the explode however doesn't work... I mean it kills you but it doesn't tear you to pieces... :P

**Comment by RPBCACUEAIIBH** [comment]
Here! I made some screenshots to show you what happens:
Shows the source:
https://drive.google.com/open?id=14fdwierUctX3_9S_BApMV9TfOVUXSx8V
Here I'm doing the mission:
https://drive.google.com/open?id=1mJhit0uAli8u9E0yNzrCX7Gd4NWguZw5
https://drive.google.com/open?id=1Bu-5nT3fFS4GPlf3xMV659a0SVaqLO6I
Watch how the HUD changes on the next 2 images:
https://drive.google.com/open?id=109mM12J1TppTJjrGySgS7TzC-HOz0dNF
https://drive.google.com/open?id=1j5-RVdiagnIB6d8m1SFvXstbml_pY6gf
Pressed "I":
https://drive.google.com/open?id=16xLcf9J1wRFhZXBgWwEcRclw1sAeD0Sh
Exited to the main menu:
https://drive.google.com/open?id=1Xj1fdCbckaIoaNPp6xCEgysy7Y-efrYG

**Comment by Amazinite** [comment]
This issue has nothing to do with `explode`.

**Comment by RPBCACUEAIIBH** [comment]
hold on... I have modified the code, and it explodes now... but I didn't modified the exploding part, something didn't let it happen I just don't know what was the problem :S
