### ISSUE TITLE
Standby for ships as alternative to parking

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#4690]
**Is your feature request related to a problem? Please describe.**
A ship is currently either active or parked, but there are situations where parking seems unfairly strong, for example:
- not having to pay for crews on parked disabled ships
- not having to pay for a parked ship that still performs an important duty like carrying important cargo

There are also other situations where keeping a ship fully active looks undesired, for example:
- a player that does some battle as a side-step in a chain of transport missions wouldn't want to take his/her transport ships into the battle

**Related Issue Links**
https://github.com/endless-sky/endless-sky/issues/4683

**Describe the solution you'd like**
Make parking somewhat more limited, and add a "standby" option that goes in-between parked and active.

Standby options differ from park in the following:
- Ships on Standby still have their crews paid in full
- Ships on Standby can be set to Active while the player is in flight (regardless of the system of the standby ship)
- Ships can be set to Standby while the player is in flight
- Non-disabled ships that go to Standby in a system with a friendly planet will land on that planet

After this feature gets implemented, then the following ships can be set to standby, but not to parked:
- Ships with (mission) cargo
- Ships that are disabled
- Ships in other systems than were the player is

Park would get the following changes:
- Ships can only be Parked if it is on the same planet as where the player is.
- Ships can only be Unparked if the player is on the same system/planet as the parked ship.

Standby options match park in the following:
- Ships that are set to StandBy will no longer show up in the active UI
- Ships that are set to StandBy will not respond to Gather/Hold/Attack or any other commands

**Describe alternatives you've considered**

- I considered not to add the "player on the same planet" limits to parking/unparking. This would allow the player to park any non-disabled ship in any system as long as it doesn't carry cargo.
- I also considered to only add the "player on the same planet" limit to parking, but not to unparking. This would require the player to get ships he/she wants to park to the same system as the flagship before landing, but would allow unparking as it is done now.

**Additional context**

For UI I would expect the current "parked" toggle to switch between 3 options, "active", "parked" and "standby".

**Comment by Amazinite** [comment]
> **Is your feature request related to a problem? Please describe.**
> A ship is currently either active or parked, but there are situations where parking seems unfairly strong, for example:
> 
> * not having to pay for crews on parked disabled ships
> * not having to pay for a parked ship that still performs an important duty like carrying important cargo
> 
> There are also other situations where keeping a ship fully active looks undesired, for example:
> 
> * a player that does some battle as a side-step in a chain of transport missions wouldn't want to take his/her transport ships into the battle

What would the difference be between telling a ship to hold and just leaving the system and this standby mode? In both cases the crew is still paid, the cargo is still carried, and the ships avoid combat, so the core of the issue is addressed by just telling the ship(s) to hold. The only thing you'd be missing is these additional features.

>Standby options match park in the following:
>
>* Ships that are set to StandBy will no longer show up in the active UI
>* Ships that are set to StandBy will not respond to Gather/Hold/Attack or any other commands

If anything, it might be easier to have some sort of fleet command to tell a ship to ignore general fleet commands, so hitting H while in combat to tell your ships to hold/unhold won't also tell your ships that you had on "standby" elsewhere to start coming to you.

I get the sense that this issue and #4683 are getting into the realm of mechanics that only only useful for large fleets, which typically aren't going to be a focus.
Also, if one wants to mainly use standby to store outfits, then a better feature to deal with this would be #4443, or the already possible mechanic of just parking a ship with the outfits installed.

**Comment by petervdmeer** [comment]
@Amazinite Telling a ship to hold in some safe system and then seeing the ship still show up in the middle of a chaotic battle-zone due to some accidental fleet command was indeed one major reason for me to think about the "standby" option.

Another reason was the option to park disabled ships. Somehow that felt a bit unfair/unbalanced. If a disabled ship is very valuable, then I would expect the player to want to rescue it, but it seems fair that some costs continue while the ship is not parked in a safe location.

I see issue #4683 and this issue apply both to large and small fleets. The main driver for those issues is not about fleet size, but about playing missions in a non-lineair way. The current game assumes that a player is either doing transport missions or combat missions, but does not seem to fully support doing a combat mission in the middle of a transport mission. (Unless the transport ships are also very capable war/combat ships.)
