### ISSUE TITLE
Pug Arfectas defending Wanderers don't fight

### ISSUE THREAD

**Issue by leklachu** [endless-sky/endless-sky#4955]
# Bug description

In the Wanderers plot, after the Pug Arfectas come to defend Ap'arak system from the Unfettered Hai, the Arfectas immediately cloak and no longer help out in battle.

## Version and detail

Worked for me playing 0.9.10. Upgraded to 0.9.11 from git a few days ago, started a new playthrough, and got to the point where the pug finally help.

Take off from Varu Tev'kei in Ap'arak after the meeting with the Pug, see the Arfectas, they cloak and don't uncloak even if Unfettered ships come and fight. They will stay and fight me if I fire on them quickly before they disappear.

# System

- Ubuntu 18.04
- Compiled from git
- Version 0.9.11, commit be62678cd998e3321d55da2d2334ce38738b8a86 Mar 19

# SaveFile

[Margaretha Waldeck~Arfecta Bug.txt](https://github.com/endless-sky/endless-sky/files/4397371/Margaretha.Waldeck.Arfecta.Bug.txt)

Savefile included for reference but won't work by itself: I hacked myself a cheaty-ship for some fun; but it's just overpowered, no fancy scripting or anything.

**Comment by leklachu** [comment]
P.S. I thought the Wanderers are supposed to turn hostile if you attack their Pug? But they don't for me now. (Think maybe they did when I played 0.9.10)

Perhaps this is to do with the split gvmt of Human Pug and Wanderer Pug? Could all the Wanderer-Pug relations be scripted to what's now Human Pug?

**Comment by Amazinite** [comment]
Should be fixed by https://github.com/endless-sky/endless-sky/commit/5a606198c43927d9c572d6a0da9c08963c542ec5, although since this is a bug that never actually hit a release version (I simply missed a spot in https://github.com/endless-sky/endless-sky/commit/f517d44c3d0cb8037a262f06e0cd7b69f7a42d13), I didn't bother with a compatibility mission fix; you'll need to go to your save file and look for
```
changes
	...
	government "Wanderer"
		"attitude toward"
			"Pug" .01
```
then change "Pug" to "Pug (Wanderer)" to fix this for your save file.

**Comment by leklachu** [comment]
Confirmed that fixes the Wanderers hating me if I attack the Pug. But the Pug still don't join in to help against the Unfettered.

**Comment by leklachu** [comment]
And if I attack the Wanderers the Pug are still cool with me.

Aha! If in governments.txt I copy Hai (Unfettered) relations to Pug to be Pug (Wanderers) then the Pug join in.

Still doesn't make the Pug defend the Wanderers from me. Perhaps the Pug (W) should like the Wanderers as well as vice versa?

**Comment by Amazinite** [comment]
879626a Got it.

**Comment by leklachu** [comment]
:-)

I'll put the Pug not defending Wanderers against player in a new issue; that's (hopefully) a less common need!
