### ISSUE TITLE
Easier Save Game Comparisons

### ISSUE THREAD

**Issue by jchamlin** [endless-sky/endless-sky#5171]
**Is your feature request related to a problem? Please describe.**

When I am attempting to see what has changed in a save game file, it is hard to compare them in a compare tool like Beyond Compare, because some of the sections are written in non-deterministic order. For example, ship outfits, explosions, the visited entries, the visited planet entries, and the harvested entries. Some sections are deterministic (sorted, or in some order that is the same every time), like the order of the ships in the fleet, the missions, the conditions, the log, etc and it makes those sections easier to compare.

Also, the missions change quite frequently and there can be large changes to those, and it is hard sometimes for a diff tool to resync after such a large amount of change, so it would be better to put the jobs/missions at the end of the file.

**Related Issue Links**

I'm not sure there is a request for this anywhere else.

**Describe the solution you'd like**

Sort or write out in a deterministic manner all entries of all sections of the save game file, so when you bring it up in a comparison tool and compare to a different save game file, the tool shows you only exactly what is changed. There will still be some noise (like ship positions), but that can be ignored by a rule.

**Describe alternatives you've considered**

Just comparing them and trying hard to ignore the noise caused by the somewhat random order some sections are written out in.

**Additional context**

Here is a screenshot of Beyond Compare showing an example of the conditions (nicely sorted and easy to compare) and ship outfits (which are identical but written out in a different ourder).

![Endless Sky Save File Compare Issue](https://user-images.githubusercontent.com/1820516/88397184-357fc100-cd89-11ea-9453-59a2df358c1a.png)

**Comment by Zitchas** [comment]
I can't say that I've ever compared the Archon outfits, but it does seem weird that they would be saved in different orders in different games. It is the same ship created by the same mission code, after all.

**Comment by jchamlin** [comment]
Internally the Ship.cpp is using a map object, and the default version of that map doesn't have any deterministic ordering. I'm going to see if there's any way to either use a map with deterministic iteration order (so the order the outfits are read in / added, is the same they are iterated in when writing them back out), or at least make sure when the map is iterated for output, the items are written out sorted by name.

**Comment by tehhowch** [comment]
@jchamlin is this resolved now?

**Comment by petervdmeer** [comment]
jchamlin mentioned outfits, explosion effects, visited systems, visited planets and harvested items as examples that showed up in various orders, so I expect that the issue is not solved for jchamlin yet.
