### ISSUE TITLE
Bugs in Format::Number mess up displayed ship stats

### ISSUE THREAD

**Issue by waterhouse** [endless-sky/endless-sky#6235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the attached pilot file, on the most recent git version, you can see the turning stat of my Blackbird flagship being displayed as "95.35 / 1066"—that is, with no cargo, the ship should have a turn rate of 1066.  (Screenshot in the screenshots section of the report.)  That number is absurd; it's probably at least missing a decimal point after the 106.

I encountered the problem in the current git version, 439387647c27869017ef357c4097d2907a7d6d21, and confirmed that the problem was introduced in commit 1873fd9ee9a9ad6a4fd210fe03f8d5a6fc7abc25 (PR: https://github.com/endless-sky/endless-sky/pull/4304 ).  On the prior commit, fcb4a9700bf1a4abb9d9e1e94440e9b4598219d6, the turn rate is displayed as "95.4 / 106.1".  I therefore suspect that the 1066 is supposed to be 106.06.

If you sell the KP-6 Photovoltaic Arrays, you can see it go to "99.36 / 1115" and then to "103.73 / 116.54".
If you then buy another LP072a Battery Pack, it goes to "1007 / 111.93".  I'd guess the 1007 should be 100.07.  (Buying another yields "96.65 / 107.68", and 100.07 is close to the middle, although it's not the exact arithmetic mean.)

While I'm at it: With 1 battery pack, no photovoltaic arrays, and 1 laser turret, the acceleration is displayed as "243.2 / 274.65", a different number of digits displayed.  Maybe it's cutting off the trailing 0 from 243.20; I guess that's intentional, just mentioning it.

This could probably be unit tested (alongside other tests introduced by 1873fd9ee9a9ad6a4fd210fe03f8d5a6fc7abc25) in tests/src/text/test_format.cpp.  I spent a few minutes and didn't manage to figure out how to run those tests.

If we look at the definition of Format::Number:
```
string Format::Number(double value)
...
        // Only show decimal places for numbers between +/-10'000.
        double decimal = modf(value, &value);
        if(decimal && value < 10000)
        {
                int tenths = static_cast<int>(decimal * 10.);
                // Values up to 1000 may have two decimal places.
                if(value < 1000)
                {
                        decimal *= 10.;
                        decimal -= static_cast<int>(decimal);
                        // Fix any floating point inaccuracy.
                        decimal = round(decimal * 100.) / 100.;
                        
                        int hundredths = static_cast<int>(decimal * 10.);
                        if(hundredths)
                                result += static_cast<char>('0' + hundredths);
                }
                if(tenths)
                {
                        result += static_cast<char>('0' + tenths);
                        result += '.';
                }
        }
        
        // Convert the number to a string, adding commas if needed.
        FormatInteger(value, isNegative, result);
        return result;
}
```
If we imagine that value = 100.06, then we get `decimal = 0.06`, then `tenths = static_cast<int>(0.06 * 10.) = static_cast<int>(0.6) = 0`.  (Note that, even if this rounded to the nearest integer, we'd still get 0 here for 100.04.  But rounding down seems deliberate—it's getting the tenths place.)  Then we see that a `.` is only ever added to the output string if tenths is not zero; yet the logic around "hundredths" may insert an additional digit (indeed, it should insert `6` for our 100.06).  (The alert reader will note that `result` collects characters in reverse order.)  That neatly explains the "106.06 -> 1066" problem.

It might work to replace `if(tenths)` with `if (tenths || hundredths)`... but then one has to hoist the definition of "hundredths" out of the `if(value < 1000)`, which then might mean hoisting the modifications to the "decimal" variable... Ok, trying this:
```
diff --git a/source/text/Format.cpp b/source/text/Format.cpp
index c05be034..50d5437b 100644
--- a/source/text/Format.cpp
+++ b/source/text/Format.cpp
@@ -135,19 +135,19 @@ string Format::Number(double value)
        if(decimal && value < 10000)
        {
                int tenths = static_cast<int>(decimal * 10.);
+               decimal *= 10.;
+               decimal -= static_cast<int>(decimal);
+               // Fix any floating point inaccuracy.
+               decimal = round(decimal * 100.) / 100.;
+                       
+               int hundredths = static_cast<int>(decimal * 10.);
                // Values up to 1000 may have two decimal places.
                if(value < 1000)
                {
-                       decimal *= 10.;
-                       decimal -= static_cast<int>(decimal);
-                       // Fix any floating point inaccuracy.
-                       decimal = round(decimal * 100.) / 100.;
-                       
-                       int hundredths = static_cast<int>(decimal * 10.);
                        if(hundredths)
                                result += static_cast<char>('0' + hundredths);
                }
-               if(tenths)
+               if(tenths || hundredths)
                {
                        result += static_cast<char>('0' + tenths);
                        result += '.';
```
That seems to work fine, although I haven't tested it broadly.

Oh, one final issue: observe how, in the lower right of my "bad" screenshot, it looks like it says "charging shields: -19.1:".  You can also see the same "19.1:" "number" displayed if you click on the D23-QP Shield Generator outfit.  The data files give .32 as the energy cost and shield regen (per frame) for that outfit; multiplying by 60 frames per second, we should get 19.2, but floating-point arithmetic gives us 19.199999 (depending on the size of your floats).  I suspect these facts are related... Haha, yes; it turns out that, ASCII-wise, `'0' + 10 = ':'`, so if we managed to round up...

If `decimal = .199999`, then we get `tenths = 0.1`, and then `decimal *= 10.` _probably_ sets `decimal = 1.99999`; then `decimal -= static_cast<int>(decimal)` (I feel like subtracting `tenths` would be more correct here) gives `decimal = .99999`; then `decimal = round(decimal * 100.) / 100.` presumably makes `decimal = 1.00000`, and then `hundredths = 10`, so `static_cast<char>('0' + hundredths)` would be `':'`.  That explains it.

If we do want to round, it seems the safest thing is to round early, and certainly not in between extracting digits. ... Ok, I'm getting into it now.  Here's what I came up with.
```
// Convert the given number to a string, with a reasonable number of decimal
// places. (This is primarily for displaying ship and outfit attributes.)
string Format::Number(double value)
{
	if(!value)
		return "0";
	
	string result;
	bool isNegative = (value < 0.);
	value = fabs(value);
	
	// Numbers <1000 get rounded to two decimal places.
	// Numbers 1000-10,000 get rounded to one decimal place.
	// Numbers over 10,000 get rounded to an integer.
	// Note that rounding a number <1000 may yield 1000; that's fine here.
	int integer;
	int tenths = 0;
	int hundredths = 0;
	if(value < 1000.)
	{
		int scaled_value = static_cast<int>(round(value * 100.));
		integer = scaled_value / 100;
		tenths = (scaled_value % 100) / 10;
		hundredths = scaled_value % 10;
	}
	else if(value < 10000.)
	{
		int scaled_value = static_cast<int>(round(value * 10.));
		integer = scaled_value / 10;
		tenths = scaled_value % 10;
	}
	else // >=10000
	{
		integer = static_cast<int>(round(value));
	}
	
	if(hundredths)
	{
		result += static_cast<char>('0' + hundredths);
	}
	if(tenths || hundredths)
	{
		result += static_cast<char>('0' + tenths);
		result += '.';
	}
	
	// Convert the number to a string, adding commas if needed.
	FormatInteger(integer, isNegative, result);
	return result;
}
```
This seems to work as desired.  We see "turning: 95.35 / 106.07" and "charging shields: -19.2", and everything else looks sane.

Shall I make a PR?  I might want a pointer as to how to run the number-formatting unit tests (I guess I do have a (headless) Linux machine sitting around, if that's necessary).

### Steps to Reproduce

1. Open the attached pilot file
2. Go into outfitter
3. Observe the unrealistic 1066 in the turning stats

### Expected Behavior

I expected to see a turning stat more like 106.

### Screenshots

Bad (1873fd9ee9a9ad6a4fd210fe03f8d5a6fc7abc25):
<img width="1280" alt="Screen Shot 2021-09-06 at 10 20 09 PM" src="https://user-images.githubusercontent.com/160180/132290686-e0fc4a94-7594-4ffb-9028-5fa5125defc7.png">

Good (fcb4a9700bf1a4abb9d9e1e94440e9b4598219d6):
<img width="1280" alt="Screen Shot 2021-09-06 at 10 25 51 PM" src="https://user-images.githubusercontent.com/160180/132290702-f18c5273-52ff-4066-bf00-7a68f8b2b86f.png">

### Link to save file

[JC Penney.txt](https://github.com/endless-sky/endless-sky/files/7119089/JC.Penney.txt)

### Operating System

Mac OS Catalina, 10.15.7 (19H15)

### Game Source

Built from source

### Game Version

commit 439387647c27869017ef357c4097d2907a7d6d21

**Comment by quyykk** [comment]
Very thorough, thank you. There is already a PR to fix this bug: #6223

>Shall I make a PR?

Good question, I have no idea since there already is a PR. Maybe it's worth it so that we can compare the performance of your solution and the PR? But I'll let others weigh in.

**Comment by Zitchas** [comment]
Thanks for the bug report.
I just ran into this myself with a dropship with 24 thrust - although I noticed it because it made it seem like the *full* acceleration was higher than the *unloaded* acceleration...

![Dropship with 24 thrust](https://user-images.githubusercontent.com/32169904/132950556-fec1d08d-bc29-42d4-a19d-bb024287c2b7.PNG)

**Comment by tehhowch** [comment]
Fixed in 5e89884bce9b04c890bd1f43b1d20db04243846e

**Comment by Anarchist2** [comment]
Issue still appears in 47c68e62d113025f463b1607d6c837ce9610146b.
Stock Scout stats:
![image](https://user-images.githubusercontent.com/60202690/133339587-6574747e-793e-4f34-ac93-62c92e9f4342.png)

**Comment by waterhouse** [comment]
Looks like, in my code, the Scout's max speed rounds to 390.

Looks like the true value is this:
```
        attributeValues.push_back(Format::Number(60. * forwardThrust / attributes.Get("drag")));
```
where forwardThrust comes from the X3700 Ion Thruster, with a thrust of 22.1, and drag is 3.4.

If we use rational numbers, 60 * 221/10 / (34/10) = 60 * 221 / 34 = 390 _exactly_.  Since the code is using floats, it seems that we actually have a case of "floating point arithmetic yielding numbers that are just a tiny bit off".

Using some printf debugging, I can annotate the new code:
```
        // at this point value = 389.99999999999994315658113919198513
        double decimal = modf(value, &value);
        // now value = 389.0
        // and decimal = 0.99999999999994315658113919198513
        if(decimal && value < 10000)
        {
                double tenths = 0.;
                // Account for floating-point representation error by adding EPS after multiplying.
                int hundredths = static_cast<int>(0.0000000001 + 10. * modf(decimal * 10., &tenths));
                if(hundredths > 9)
                {
                        hundredths = 0;
                        ++tenths;
                }
                
                // Values up to 1000 may have two decimal places.
                bool two = value < 1000 && hundredths;
                if(two)
                        result += static_cast<char>('0' + hundredths);
                if(two || tenths)
                {
                        result += static_cast<char>('0' + tenths);
                        result += '.';
                }
                // and now tenths = 10.0, hundredths = 0, result = ":."
        }
```
It seems that adding 0.0000000001 likely changed something from 0.9999999999999ish to 1.0ish (or rather from 9.999999999999ish to 10.0ish).

Well, generically, we can say that if the `if(hundredths > 9) { ... ++tenths; }` codepath ever gets executed, if `tenths` is 9 at that point, then you're going to end up with tenths = 10, which then produces the `:` "digit".  The code doesn't account for that possibility.

The kludge way to fix this would be to add "if tenths >= 10, then ++value and tenths = 0".  Then, if we felt up to it, "if value _now_ exceeds 1000 or 10000, reconsider some decisions".  It would suck.  That's why I recommend doing all the rounding (or truncating) in one step, prior to extracting any decimals.

The elegant fix, if we're sticking with rounding down (which seems reasonable), is to unconditionally multiply `value` by 100 at the start, throw away the decimal, and then we can use nice perfect integers to decide how many decimals to write and how many there will be.  And if you think there are a bunch of "x.99999999999" values that would be worth rounding up to "x+1", then you could do that "add 0.0000000001" step at the start, just before tossing the decimal.

```
string Format::Number(double value)
{
	if(!value)
		return "0";
	
	string result;
	bool isNegative = (value < 0.);
	value = fabs(value);
	// We'll show up to two decimal places, truncating the rest.
	// We add a small value so that numbers like 389.9999999999
	// (introduced by floating-point inaccuracy) won't round down.
	int scaled_value = static_cast<int>(value * 100. + 0.00000001);
	int integer = scaled_value / 100;
	int tenths = 0;
	int hundredths = 0;
	// Only show decimals for numbers between +/-10'000.
	if (integer < 10000)
	{
		int decimal = scaled_value % 100;
		tenths = decimal / 10;
		// Values up to 1000 may have two decimal places.
		if (integer < 1000)
		{
			hundredths = decimal % 10;
		}
	}

	if(hundredths)
	{
		result += static_cast<char>('0' + hundredths);
	}
	if(tenths || hundredths)
	{
		result += static_cast<char>('0' + tenths);
		result += '.';
	}	
	
	// Convert the number to a string, adding commas if needed.
	FormatInteger(integer, isNegative, result);
	return result;
}
```
With the above, the Scout's max speed does show as 390.  (If I just use `scaled_value = static_cast<int>(value * 100.)`, then it becomes 389.99.)

Thoughts?

**Comment by tehhowch** [comment]
What's fun is that a test case for that exact calculation passes, but the game continues to encounter the issue. Was able to find a way to reproduce the issue in a unit test, so we can avoid breaking it in any future refactorings: d4c8abdd5bba29aa5cbff28f13d2add164ff0454

**Comment by tehhowch** [comment]
>  "if value now exceeds 1000 or 10000, reconsider some decisions".
It's not that critical IMO.
(Also, the value couldn't exceed 1000 or 10000 due to the tenths correction, it could only _equal_ either of them, which means there will be no decimals displayed anyway.)

**Comment by quyykk** [comment]
Well, that was the last bug. To make sure such a bug doesn't appear again I tested the newest `Number` function with fuzzy testing and it ran for a minute without crashing (for comparison, the previous function crashed in under a second).

Yay! :)
