### ISSUE TITLE
Rebalancing/Removing the Bellows-Class Afterburner

### ISSUE THREAD

**Issue by the2nake** [endless-sky/endless-sky#8042]
### Problem Description

I've always enjoyed the ability to use less than 10 outfit space and add over 500,000 thrust to my ships, allowing me to save significant amounts of outfit space. The Bellows-Class Afterburner can even be used as a thruster replacement to increase thrust for the same outfit space used (afterburner + fuel modules), and to increase engine space for steering.

This is slightly overpowered.

### Related Issue Links

[#7574](https://github.com/endless-sky/endless-sky/issues/7574): Changing the Remnant afterburners to work in burst wouldn't really change their incredible effectiveness as afterburners. They still provide more than enough thrust to get out of a tight spot, and are arguably more effective when combined with medium-sized thrusters than larger thrusters.

Though I am of the opinion that the fuel usage of the Remnant afterburners is too low a price to pay for incredible agility, I realize that many people disagree. However, afterburners don't need to be used consistently, and a small burst of speed in tight spots is all heavy warships really need.

### Desired Solution

A potential solution to this problem is to reduce the amount of thrust the Bellows-Class Afterburner gives, (perhaps down to 300,000 thrust?) and adjust its fuel and energy usage, and its heat output, accordingly. This would still make it much better than any human afterburners, while not making it too powerful.

Because the Merganser should keep its incredible agility, I would suggest adding the `inertia reduction` attribute to the ship to make it just as manoeuvrable with a weaker afterburner (and perhaps give it weaker engines to compensate?)

### Alternative Approaches

As discussed in #7574, afterburners can be changed to work in burst only. Though I completely support this change, it will not affect the balance of the afterburner when used as intended.

The outfit space used could be increased to 20 or so. This would require that the Merganser has more engine and outfit space, which would have an impact on its effectiveness as a fighter (it could then be rearranged to regenerate shields quite a bit faster using Coalition outfits)

The Remnant afterburner can also just be removed, and the Merganser can be given in-built afterburners. I don't really agree with this, because I would like the Remnant to get their own afterburners, especially as it fits with their way of thinking.

**Comment by Zitchas** [comment]
The bellows, with it's rather massive fuel draw, is supposed to be used as a "jump" type action for use in dodging rather than prolonged use when cruising. I've been contemplating whether the burst mechanism would be appropriate for it, but that would also impair its universal ability and basically force the creation of a whole afterburner family like the other areas have done. I'm not a huge fan of that idea, but that may well be where this ends up going.

On the larger scale, one thing that may really be required for the bellows to truly have a unique spot and not just be overpowered afterburners is a larger scale rework of how afterburners work. Most importantly, perhaps, is implementing a restriction that the boost to a ship's max speed only applies for as long as the afterburners are working, and has a relatively fast decay after they stop. This would make the relative fuel consumption a lot more significant, since if one wants to use afterburners as thrusters, one would *have* to run them constantly.

**Comment by Saugia** [comment]
I would very much prefer we don't do that as I really wanted to reserve a burst type afterburner unique for the low tier Gegno that I've been talking about for several months now. If someone else will use the same thing, there goes that idea completely, and I don't think there's another way I could make one unique besides lazy stat manipulation and not something fun like burst firing.

**Comment by the2nake** [comment]
> The bellows, with it's rather massive fuel draw, is supposed to be used as a "jump" type action for use in dodging rather than prolonged use when cruising.

I agree. Making the thrust lower (along with a lower fuel draw) would essentially make it more a cruise-type afterburner.

> I would very much prefer we don't do that as I really wanted to reserve a burst type afterburner unique for the low tier Gegno that I've been talking about for several months now.

Perhaps we address both these issues? I'm thinking of making the bellows afterburners burn more fuel, use more energy, and generate more heat the longer each burst of usage is. This wouldn't make it have bursts, per se, but using it for extended periods would be unadvisable.

The only issue is that I'm fairly certain that there's no code that does this yet. There _is_ burn and ion damage (not sure for fuel), but those come with the gfx (not sure if those can be hidden) and last after the afterburners have been stopped.

**Comment by Zitchas** [comment]
I'd prefer to not have increased energy consumption. The Remnant are energy-starved as it is. Ramping fuel consumption, though, would be a very interesting mechanic to have and very appropriate here.

**Comment by Zireael07** [comment]
Actually, you might have hit a nail on the head @opusforlife2. I googled a bit and came across this: https://www.spaceflightinsider.com/missions/how-to-slow-down-an-interstellar-spacecraft-at-alpha-centauri/

(Not magic: just deploying a solar sail in a , uh, reverse configuration, so instead of photons speeding us up bit by bit they slow us down bit by bit)

**Comment by Zitchas** [comment]
Unfortunately, one of the principle conceits of Endless Sky is that space is not a vacuum. Effectively it is a medium that has resistance. It's not a lore thing, just a mechanics thing in how all ships (and some weapons) have drag. This is why ships when disabled slow to a stop (which also shouldn't happen according to Newton), and for that matter why we have a max speed. Realistically, we should be able to accelerate forever, with gradually decreasing returns.

**Comment by Zireael07** [comment]
Most space games I know (Naev, Endless Sky, Stellar Frontier) have drag. Actually, _is_ there a 2D space game that doesn't? :thinking:

**Comment by Saugia** [comment]
Game design. ES is not realistic, it is an arcade game, and based on similarly styled games. Game design>Realism. We aren't trying to make it realistic.

**Comment by vitalchip** [comment]
Drag is multi purpose, in the simplest sense it allows for there to be different top speeds for different ships. In this way we can make sure that an interceptor, for example, can always catch a freighter over the short distances in which the game operates.

The main use for it though it to give the ships 'grip' and allow them to turn and change course without any of the complexity of counter thrusting or complex course projections. This saves a lot of work for the Ai as we can use a simple point and thrust method.

**Comment by vitalchip** [comment]
If two ships have unlimited top speed then the faster accelerating ship will indeed catch the slower accelerating ship, at a point. If the slower accelerating ship stops accelerating at a given speed and the faster accelerating ship does not stop accelerating until a much higher speed then the intercept point will be sooner. That's why I mentioned the short distances in the game, it's relevant in that context. Given unlimited distances it would matter much less but we also have constrained distances.

Drag is applied whenever acceleration is present, which is what you're seeing.

Directional changes need no calculation when drag is involved because any velocity other than in the direction of acceleration is 'scrubbed off' so all that's required is to point at the destination and accelerate.

Without drag you'd need to plot a course which countered any existing (undesired) velocity.

**Comment by vitalchip** [comment]
Yes, distances are small by design it's why everything tends to end up in a ball near the centre, or at least around a planet. There's also a constraint 'fence' to stop (most) ships wandering too far out.

Drag applies a deceleration, normal to your heading at 0.5x your acceleration, so for example if you acceleraate 'north' then come off the controls, turn the ship to poinr 'east' you'll be pointing 'east' but moving 'north'. Then accelerate and your 'north' component will be reduced as you acceleraate until your entire velocity is 'east'.

So by simply 'keeping the nose' pointed t the target and accelerating you'll (fairly quickly) have a velocity direction straight at it. 

The alternative in the above case would be to point the ship somewhere 'south east' depending on the distances and velocity to arrive at the destination. You can imagine the disadvantages if the destination is a ship you plan on shooting as your nose (and therefore guns) will almost never be pointed at it.

**Comment by Zitchas** [comment]
How hard would it be to try that out? Not referring to getting the AI to handle it or anything; just enough to be able to experience it in flight. Is it as simple as just removing the drag attribute?

**Comment by vitalchip** [comment]
If you change this:

https://github.com/endless-sky/endless-sky/blob/c17c7eccae744ebdb4e7546e3002dc5e7a0aee1d/source/Ship.cpp#L2066

To: velocity += acceleration;

You can experience no drag but it will be 'unlimited'. Speeds will get excessive and it'll be hard to come to a complete stop.

For a 'safer' experience I change it to:

			if(velocity.Length() > MaxVelocity() || velocity.Length() < 0.1)
                 velocity += dragAcceleration;
			 else
				 velocity += acceleration;

This will provide a drag free experience up to the ship's max speed (as it would have been under drag) and also allow the ship to stop completely with greater ease. 

You can do velocity.Length() > MaxVelocity() * 2 (or whatever) if you want to allow multiples of the max speed

**Comment by vitalchip** [comment]
Oh, once you've changed it and had a play around with a ship.. go to Mesuket and watch the fun of so many Ai ships with no drag.

**Comment by Ferociousfeind** [comment]
something something, want lateral thrusters, and also want drag to be explicitly a function of your thrusters preventing excessive speeds and canceling lateral velocity...

**Comment by Zitchas** [comment]
I must say: The big Pug battles are a lot of fun with this. They seem to spread out a bit more, fewer death balls. My personal skill feels like it makes a lot more impact on the battle, and a lot less dependant on RNG. I can actually make tactical decisions about what I'm doing in battle, which is novel. Having big fleet vs fleet battles turn into a dozen little clumps instead of one giant death ball is a great improvement. It also makes shipslike the rainmaker a bit more powerful since they can shift targets a lot faster.

**Comment by Luuiscool4567** [comment]
Has this been fixed with the afterburner nerf?

**Comment by the2nake** [comment]
I will check.

**Comment by the2nake** [comment]
No, this is not fixed.

**Comment by Zitchas** [comment]
Given that the intention of the Bellows is *not* to be just another afterburner in the same line as the regular ones, I don't see anything beyond the nerf that already happened being done.

**Comment by the2nake** [comment]
I guess the real thing here is just to have each afterburner have its own *flavour*, so to speak. Right now they all feel sort of the same, except with stat changes, so it would be more interesting (in terms of gameplay and lore) to have different species' afterburners behave significantly differently. For example, humans might have just extra thrust, Remnant might have an increasing slow resistance the longer the afterburner is applied with only slightly higher afterburner thrust, etc.

**Comment by Quantumshark** [comment]
Is this resolved by the changes in #9693, or do you still feel that the Bellows is too strong?

**Comment by the2nake** [comment]
I think those changes were sufficient. I still don't feel like the afterburners are super unique at the moment, but I admittedly have not implemented any concepts myself to see if they work well. For the problem described at the beginning, I'd say there's no more point in keeping this open.
