### ISSUE TITLE
Sequence bug with `to display` feature

### ISSUE THREAD

**Issue by MasterOfGrey** [endless-sky/endless-sky#8443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is a bug which has been raised many times on Discord and was very elusive to understand.

Eventually @Hurleveur and @Zitchas got down to a possible explanation: 
![image](https://user-images.githubusercontent.com/60949828/220613221-d1943159-b9d7-4e35-9c53-ab5f168a9751.png)
But I can't find evidence that anyone logged it, or that anyone who saw was able to fix it.

Essentially, when selecting an option in some choice blocks that utilise `to display` to hide options - sometimes you get an inappropriate outcome to what you chose.

This appears to be a *code* bug, the mission syntax does not appear to be the cause of the issue.

Anecdotally it's been reported on other convos, but we've only managed to track it down the one time with "Hai Reveal [C05] Cleanup"

### Steps to Reproduce

Best guess?

![image](https://user-images.githubusercontent.com/60949828/220613932-9b20b805-fc68-4456-8912-d0fd1f4161b6.png)

### Expected Behavior

The conversation should show the correct text choice option you selected.

### Link to save file

This provided by Z:
[Rebbia_Rampart3031-09-12_Jumping_to_Final_Justice.txt](https://github.com/endless-sky/endless-sky/files/10803362/Rebbia_Rampart3031-09-12_Jumping_to_Final_Justice.txt)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

Continuous

### Additional Information

Note; this is separate from the issue that there probably needs to be additional text outcomes from decisions now that there's a greater spread of nuance in choices, but I'm not keen to rework them and test it when I can't trust the game to actually show the correct thing.

**Comment by MasterOfGrey** [comment]
@UnorderedSigh I'll ping you since weird code bugs that affect this are probably in your wheelhouse

**Comment by UnorderedSigh** [comment]
I'm unable to reproduce this. I need to know the *exact sequence of actions* you use when you enter the mission (mouse clicks, up or down, keystrokes, etc.) Also, I need to know *which* number keys you are using. Is it the keypad or the numbers above the qwerty region? Or are you using a non-standard keyboard layout?

**Comment by warp-core** [comment]
You probably can't reproduce it because it was fixed in #8291.

**Comment by UnorderedSigh** [comment]
@MasterOfGrey can you confirm this still happens at the top of master, built from source?

I do see another possible reason: the code assumes the numerical values of the SDL_Keycode are sequential with none in between, which may not be the case for all keyboards.

**Comment by UnorderedSigh** [comment]
Actually, confirming it happens with 0.10.0 should be sufficient since #8291 was in that version.

**Comment by MasterOfGrey** [comment]
> You probably can't reproduce it because it was fixed in #8291.

Ah, this one came and went past me without me ever knowing what it was about. I was working through my list of items and searched for terms related to this bug and couldn't see anything come up that matched.

If that was indeed the fix then all good, apologies.
(If I hear of the bug happening again though I'll refer that to here.)
