### ISSUE TITLE
Outfits that add hull will result in a disabled ship on launch if too many are purchased.

### ISSUE THREAD

**Issue by KAWilley** [endless-sky/endless-sky#88]
Exactly what it says on the tin. If outfits that increase hull are added to the game, they have a potential to disable the player's ship due to it having too low hull.

Also, an outfit that reduces the required crew of a vessel will not automatically fire the extra crew that would result (though I believe that removing turrets will automatically do so).

**Comment by endless-sky** [comment]
The hull bug should be fixed in commit b4dbec4. A ship's hull amount is now changed whenever an outfit that provides hull is added or removed. Note that this means if you plunder hull plating from a disabled ship, it might explode the moment you're done boarding it. But I guess that's a reasonable behavior.

For the crew, there are some cases where you would want to fire the extra crew, and some where you would not. The ship info sidebar actually shows (required crew / bunks), not (actual crew / bunks), which is why the number updates when you buy or sell turrets. But your crew count does not change when you do that - instead, if you are short, more crew get added right before you take off from the planet.

**Comment by KAWilley** [comment]
Still not working when leaving planets, but only when large numbers of hull improvements are provided.

**Comment by endless-sky** [comment]
They're 30 T each; how could you fit 24 of them on a Fury? I've tried testing with smaller numbers of them, and no longer see the disabled ship bug after that bug fix from two days ago.

**Comment by KAWilley** [comment]
Ah. I'm using my cheat plugin that allows you to extend the available space of a ship.

This may be a separate issue, but should capacity in and of itself impact the rate at which a ship can rotate/accelerate?

**Comment by endless-sky** [comment]
Capacity does not, but mass does. So, for example, the mass expansion will cause your turn and acceleration to decrease, because in addition to adding 15 to outfit space and subtracting 20 from cargo space, it adds 5 to your mass.
